name: ffi_test_pkg
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  ffi: ^2.1.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
